name: Triage
on:
  issues:
    types: [opened]
jobs:
  add-to-project:
    name: Add issue to triage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/The-FireHub-Project/projects/2
          github-token: ${{ secrets.GH_TOKEN }}
          labeled: "status: Waiting Triage"